### PR TITLE
loading match pages offline

### LINKED ISSUE #1224: Match pages fail to load offline
If you go to a match page (e.g.  online, go offline, and return to/reload the match page, it will be stuck on the loading page. @calebeby thinks this is due to the analysis page. I can't currently fully repro this on dev - the match info and score panels still load, but on the latest deploy preview nothing loads whatsoever besides the loading indicator.

### LINKED ISSUE #1484: video covers analysis table when offline
image
https://dev.peregrinefrc.com/events/2019orwil/matches/qm2
Hiding the videos offline should fix this.

### PR DESCRIPTION
**Pull request by varCepheid**
closes #1224
closes #1484

### CODE REVIEW

**Comment by varCepheid** [comment]
Everything worked well for me for that one page. Last fix is to make the card that the text appears on a little wider and the text bold.

**Comment by varCepheid** [comment]
Tested on that one match page as well as another, it's working how I think it should.

File: src/utils/use-network-connection.ts [hunk 1]
```diff
@@ -64,7 +67,10 @@ export const useNetworkConnection = () => {
     const connection = navigator.connection
     const updateConnectionStatus = () => {
       if (navigator.onLine) {
-        if (connection?.effectiveType === '4g') {
+        if (
+          connection?.effectiveType === '4g' &&
+          (connection.type === 'wifi' || connection.type === 'ethernet')
```
Comment (calebeby) [inline src/utils/use-network-connection.ts:72]: @varCepheid This doesn't seem to work quite right, when I am on my laptop on wifi, the video doesn't load automatically. `navigator.connection.effectiveType` is `4g` on my computer and `navigator.connection.type` is not defined. https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/type#browser_compatibility. It looks like that property is not supported on most computers (but it is on phones, except iphones). Is there different logic we can use when connection.type is not defined?

Comment (varCepheid) [reply src/utils/use-network-connection.ts:72]: Simplest fix I see is running only the first condition when `connection.type` is undefined. Any issue with that? It fixes the issue on my computer, but I don't have a good way to test at the moment on a phone.

Comment (calebeby) [reply src/utils/use-network-connection.ts]: 👍 Sure, works for me. But that means that on iphones it will always load by default 😬 I guess that is fine 🤷

File: src/routes/event-match.tsx [hunk 2]
```diff
@@ -229,9 +246,28 @@ const EventMatch = ({ eventKey, matchKey }: Props) => {
...
+            >
+              <p>
+                <em>
+                  <b>
+                    Analysis table, videos, and reports are only available
+                    online.
+                  </b>
+                </em>
+              </p>
+            </Card>
```
Comment (calebeby) [inline src/routes/event-match.tsx:270]: @varCepheid Great job with adding this card to inform the user why stuff is missing. I have some feedback on the visual design and text:

- I think it looks better without the italics
- Can we move it to the top above the match info card? Also I think it would look good to have the same width as the other cards.
- Can we add an icon in front of the message? We have an `<Icon>` component to display an icon and you could use [this icon](https://materialdesignicons.com/icon/cloud-off-outline) (or another one)
- What do you think about changing the text like this (the cloud emoji would be the slashed cloud icon):
   :cloud: **No connection** Showing limited information
- Can we use consistent padding all the way around the element? The `<p>` tag is adding extra margin above/below (we don't need a `<p>` tag here).

**Comment by calebeby** [comment]
@varCepheid Great work with this, it is looking really good.

- I think changing the 2nd line of text to "Showing limited information" would be a little easier to read than "Analysis table, videos, and reports are only available online." For some reason, when I read "Analysis table, videos, and reports are only available online" my brain reads it as meaning "only Analysis table, videos, and reports are available online" and then my brain has to parse it another time to understand it right.
- The cloud icon and the "no connection" text are not aligned, it would be nice for the midline of the text to be aligned with the middle of the icon. You can use flexbox or grid to implement this (happy to help/provide more details if you want)
   screenshot
- Generally, unless there is semantic meaning associated with bolded text or semantic breaks in phrasing, `<b>` and `<br>` should be avoided. Those elements came from an era when the HTML elements themselves were concerned with visual display more than semantic meaning. With HTML 5, the meaning of those elements has been adjusted, and in cases like this where we just want bolded text and a split line (no semantic meaning), it is better to use elements without semantic meaning like `<div>` and `<span>` with styling applied in CSS. Do you mind switching to div and/or span?

File: src/routes/event-match.tsx [hunk 3]
```diff
@@ -1,3 +1,4 @@
+/* eslint-disable caleb/@typescript-eslint/restrict-plus-operands */
```
Comment (calebeby) [inline src/routes/event-match.tsx:1]: I think this eslint-disable comment is no longer needed.

File: src/routes/event-match.tsx [hunk 4]
```diff
@@ -39,6 +44,35 @@ const blueStyle = css``
...
+  grid-template-columns: auto;
+  grid-template-areas:
+    'topArea'
+    'leftColumn';
+  padding: 0.75rem;
+  @media (max-width: 930px) {
+    grid-template-columns: 1fr;
+    grid-template-areas:
+      'topArea'
+      'leftColumn';
```
Comment (calebeby) [inline src/routes/event-match.tsx:69]: This grid-template-areas property is the same as the one outside of the media query, so there is no need to override it here.

File: src/routes/event-match.tsx [hunk 5]
```diff
@@ -142,15 +189,33 @@ const EventMatch = ({ eventKey, matchKey }: Props) => {
...
         <>
+          {!isOnline && (
+            <div class={offlineDisplayInfo}>
+              <Card
+                class={css`
+                  justify-self: center;
+                  padding: 1rem;
+                  text-align: center;
+                `}
+              >
```
Comment (calebeby) [inline src/routes/event-match.tsx:210]: Would it work to combine the outer div and the card into just the card?

```js
<Card class={offlineDisplayInfo}>
```
And move the CSS properties from the inline block up to the offlineDisplayInfo style block?

Comment (calebeby) [reply src/routes/event-match.tsx:210]: On screen sizes < 540px and > ~500px, the edges of the offline card don't line up with the edges of everything else. I think combining the outer div with the card may fix that, but in case it doesn't, can you fix that as well?

**Comment by calebeby** [comment]
Also, your approach is totally valid but I am curious whether it would simplify the CSS to move the offline stuff into the left column div. There may be a reason why that won't work that I haven't thought of, but just curious

**Comment by varCepheid** [comment]
I don't think it would simplify. It makes sense to me to leave that piece alone and not possibly throw in a card that we don't always want to display.

File: src/routes/event-match.tsx [hunk 6]
```diff
@@ -90,22 +102,54 @@ const matchWithVideoStyle = css`
...
+  }
+`
+
+const offlineDisplayInfo = css`
+  grid-area: topArea;
+  display: grid;
+  grid-template-areas:
+    'iconArea title'
+    'detail detail';
+  justify-self: center;
```
Comment (calebeby) [inline src/routes/event-match.tsx:121]: Can you add `align-items: center` so that the "No connection" text is vertically centered with the icon?

**Comment by calebeby** [comment]
The width difference here doesn't look great IMO. Mind switching it back to match the width? (adding it to the leftColumn might be the easiest way but I could be wrong)

screenshot

**Comment by calebeby** [comment]
Can you use grid-gap on the no connection card to add an equal gap between all the items, and also add padding to the card, and remove the padding on the individual children of the card?

**Review by calebeby — APPROVED** [review]
Great work! Thanks for putting up with all my nitpicky feedback :wink: 

Feel free to merge
